import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dotenv from 'dotenv';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
dotenv.config();


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Educational System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
